"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-28 11:25:47.323346
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import fleet_service.db.types

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aircraft",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("callsign", sa.String(length=32), nullable=False),
        sa.Column(
            "airframe",
            sa.Enum(
                "fixed_wing",
                "multirotor_hexa",
                "multirotor_quad",
                name="airframe",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("mavlink_system_id", sa.Integer(), nullable=True),
        sa.Column("mavlink_connection", sa.String(length=200), nullable=True),
        sa.Column("swarm_drone_id", sa.Integer(), nullable=True),
        sa.Column("cruise_speed_mps", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", fleet_service.db.types.UTCDateTime(length=27), nullable=False),
        sa.Column("updated_at", fleet_service.db.types.UTCDateTime(length=27), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_aircraft")),
        sa.UniqueConstraint("callsign", name=op.f("uq_aircraft_callsign")),
        sa.UniqueConstraint("mavlink_system_id", name=op.f("uq_aircraft_mavlink_system_id")),
        sa.UniqueConstraint("swarm_drone_id", name=op.f("uq_aircraft_swarm_drone_id")),
    )
    op.create_table(
        "aircraft_groups",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", fleet_service.db.types.UTCDateTime(length=27), nullable=False),
        sa.Column("updated_at", fleet_service.db.types.UTCDateTime(length=27), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_aircraft_groups")),
        sa.UniqueConstraint("name", name=op.f("uq_aircraft_groups_name")),
    )
    op.create_table(
        "audit_events",
        sa.Column("seq", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("ts", fleet_service.db.types.UTCDateTime(length=27), nullable=False),
        sa.Column("actor_user_id", sa.String(length=36), nullable=True),
        sa.Column("actor_username", sa.String(length=64), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=True),
        sa.Column("entity_id", sa.String(length=36), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("source_ip", sa.String(length=64), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("seq", name=op.f("pk_audit_events")),
        sa.UniqueConstraint("event_id", name=op.f("uq_audit_events_event_id")),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_events_action"), ["action"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_events_actor_user_id"), ["actor_user_id"], unique=False
        )
        batch_op.create_index("ix_audit_events_entity", ["entity_type", "entity_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_ts"), ["ts"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "observer",
                "operator",
                "supervisor",
                "admin",
                name="role",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", fleet_service.db.types.UTCDateTime(length=27), nullable=False),
        sa.Column("updated_at", fleet_service.db.types.UTCDateTime(length=27), nullable=False),
        sa.Column("last_login_at", fleet_service.db.types.UTCDateTime(length=27), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "aircraft_group_members",
        sa.Column("group_id", sa.String(length=36), nullable=False),
        sa.Column("aircraft_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["aircraft_id"],
            ["aircraft.id"],
            name=op.f("fk_aircraft_group_members_aircraft_id_aircraft"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["aircraft_groups.id"],
            name=op.f("fk_aircraft_group_members_group_id_aircraft_groups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("group_id", "aircraft_id", name=op.f("pk_aircraft_group_members")),
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "link_stale",
                "link_lost",
                "battery_low",
                "battery_critical",
                "gps_lost",
                "geofence_breach",
                "mission_complete",
                "route_deviation",
                "deconfliction_risk",
                "command_timeout",
                "control_orphaned",
                "video_down",
                name="alertkind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "info", "warning", "critical", name="alertseverity", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "active", "acknowledged", "cleared", name="alertstate", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("aircraft_id", sa.String(length=36), nullable=True),
        sa.Column("dedupe_key", sa.String(length=128), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("raised_at", fleet_service.db.types.UTCDateTime(length=27), nullable=False),
        sa.Column("acknowledged_by", sa.String(length=36), nullable=True),
        sa.Column("acknowledged_at", fleet_service.db.types.UTCDateTime(length=27), nullable=True),
        sa.Column("cleared_at", fleet_service.db.types.UTCDateTime(length=27), nullable=True),
        sa.ForeignKeyConstraint(
            ["acknowledged_by"], ["users.id"], name=op.f("fk_alerts_acknowledged_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["aircraft_id"],
            ["aircraft.id"],
            name=op.f("fk_alerts_aircraft_id_aircraft"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_alerts_aircraft_id"), ["aircraft_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_dedupe_key"), ["dedupe_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_state"), ["state"], unique=False)

    op.create_table(
        "commands",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "arm",
                "disarm",
                "takeoff",
                "hold",
                "resume",
                "return_to_launch",
                "land",
                "goto",
                "mission_upload",
                "mission_start",
                "mission_pause",
                "geofence_upload",
                name="commandkind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("issued_by", sa.String(length=36), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "awaiting_confirmation",
                "in_progress",
                "completed",
                "rejected",
                "expired",
                name="commandstate",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("confirmation_required", sa.Boolean(), nullable=False),
        sa.Column("confirmed_at", fleet_service.db.types.UTCDateTime(length=27), nullable=True),
        sa.Column("created_at", fleet_service.db.types.UTCDateTime(length=27), nullable=False),
        sa.Column("completed_at", fleet_service.db.types.UTCDateTime(length=27), nullable=True),
        sa.ForeignKeyConstraint(
            ["issued_by"], ["users.id"], name=op.f("fk_commands_issued_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commands")),
    )
    with op.batch_alter_table("commands", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_commands_issued_by"), ["issued_by"], unique=False)

    op.create_table(
        "control_leases",
        sa.Column("aircraft_id", sa.String(length=36), nullable=False),
        sa.Column("holder_user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "state",
            sa.Enum("held", "orphaned", name="leasestate", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("acquired_at", fleet_service.db.types.UTCDateTime(length=27), nullable=False),
        sa.Column("holder_seen_at", fleet_service.db.types.UTCDateTime(length=27), nullable=False),
        sa.Column("pending_request_by", sa.String(length=36), nullable=True),
        sa.Column(
            "pending_request_at", fleet_service.db.types.UTCDateTime(length=27), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["aircraft_id"],
            ["aircraft.id"],
            name=op.f("fk_control_leases_aircraft_id_aircraft"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["holder_user_id"], ["users.id"], name=op.f("fk_control_leases_holder_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["pending_request_by"],
            ["users.id"],
            name=op.f("fk_control_leases_pending_request_by_users"),
        ),
        sa.PrimaryKeyConstraint("aircraft_id", name=op.f("pk_control_leases")),
    )
    with op.batch_alter_table("control_leases", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_control_leases_holder_user_id"), ["holder_user_id"], unique=False
        )

    op.create_table(
        "incidents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active", "suspended", "closed", name="incidentstatus", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("base_latitude", sa.Float(), nullable=False),
        sa.Column("base_longitude", sa.Float(), nullable=False),
        sa.Column("base_altitude_amsl_m", sa.Float(), nullable=True),
        sa.Column("operating_radius_m", sa.Float(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", fleet_service.db.types.UTCDateTime(length=27), nullable=False),
        sa.Column("updated_at", fleet_service.db.types.UTCDateTime(length=27), nullable=False),
        sa.Column("closed_at", fleet_service.db.types.UTCDateTime(length=27), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_incidents_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incidents")),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", fleet_service.db.types.UTCDateTime(length=27), nullable=False),
        sa.Column("last_seen_at", fleet_service.db.types.UTCDateTime(length=27), nullable=False),
        sa.Column("expires_at", fleet_service.db.types.UTCDateTime(length=27), nullable=False),
        sa.Column("revoked_at", fleet_service.db.types.UTCDateTime(length=27), nullable=True),
        sa.Column("user_agent", sa.String(length=256), nullable=True),
        sa.Column("source_ip", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sessions_token_hash")),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "video_streams",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("aircraft_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=False),
        sa.Column("relay_path", sa.String(length=64), nullable=False),
        sa.Column(
            "codec",
            sa.Enum("h264", "h265", "unknown", name="videocodec", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", fleet_service.db.types.UTCDateTime(length=27), nullable=False),
        sa.Column("updated_at", fleet_service.db.types.UTCDateTime(length=27), nullable=False),
        sa.ForeignKeyConstraint(
            ["aircraft_id"],
            ["aircraft.id"],
            name=op.f("fk_video_streams_aircraft_id_aircraft"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_video_streams")),
        sa.UniqueConstraint("relay_path", name=op.f("uq_video_streams_relay_path")),
    )
    with op.batch_alter_table("video_streams", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_video_streams_aircraft_id"), ["aircraft_id"], unique=False
        )

    op.create_table(
        "command_targets",
        sa.Column("command_id", sa.String(length=36), nullable=False),
        sa.Column("aircraft_id", sa.String(length=36), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "pending",
                "dispatched",
                "acked",
                "nacked",
                "timeout",
                "rejected",
                name="commandtargetstate",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("updated_at", fleet_service.db.types.UTCDateTime(length=27), nullable=False),
        sa.ForeignKeyConstraint(
            ["aircraft_id"], ["aircraft.id"], name=op.f("fk_command_targets_aircraft_id_aircraft")
        ),
        sa.ForeignKeyConstraint(
            ["command_id"],
            ["commands.id"],
            name=op.f("fk_command_targets_command_id_commands"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("command_id", "aircraft_id", name=op.f("pk_command_targets")),
    )
    op.create_table(
        "geofences",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("incident_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("inclusion", "exclusion", name="geofencekind", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("geometry", sa.JSON(), nullable=False),
        sa.Column("max_altitude_relative_m", sa.Float(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", fleet_service.db.types.UTCDateTime(length=27), nullable=False),
        sa.Column("updated_at", fleet_service.db.types.UTCDateTime(length=27), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"], ["incidents.id"], name=op.f("fk_geofences_incident_id_incidents")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_geofences")),
    )
    with op.batch_alter_table("geofences", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_geofences_incident_id"), ["incident_id"], unique=False)

    op.create_table(
        "search_areas",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("incident_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("geometry", sa.JSON(), nullable=False),
        sa.Column("area_m2", sa.Float(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "unassigned",
                "assigned",
                "in_progress",
                "searched",
                name="searchareastatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", fleet_service.db.types.UTCDateTime(length=27), nullable=False),
        sa.Column("updated_at", fleet_service.db.types.UTCDateTime(length=27), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"], ["incidents.id"], name=op.f("fk_search_areas_incident_id_incidents")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_areas")),
    )
    with op.batch_alter_table("search_areas", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_search_areas_incident_id"), ["incident_id"], unique=False
        )

    op.create_table(
        "missions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("incident_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "waypoint",
                "area_search",
                "swarm_area",
                name="missionkind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "planned",
                "active",
                "paused",
                "completed",
                "aborted",
                name="missionstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("search_area_id", sa.String(length=36), nullable=True),
        sa.Column("default_altitude_relative_m", sa.Float(), nullable=False),
        sa.Column("default_speed_mps", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", fleet_service.db.types.UTCDateTime(length=27), nullable=False),
        sa.Column("updated_at", fleet_service.db.types.UTCDateTime(length=27), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_missions_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"], ["incidents.id"], name=op.f("fk_missions_incident_id_incidents")
        ),
        sa.ForeignKeyConstraint(
            ["search_area_id"],
            ["search_areas.id"],
            name=op.f("fk_missions_search_area_id_search_areas"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_missions")),
    )
    with op.batch_alter_table("missions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_missions_incident_id"), ["incident_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_missions_search_area_id"), ["search_area_id"], unique=False
        )

    op.create_table(
        "tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("mission_id", sa.String(length=36), nullable=False),
        sa.Column("aircraft_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "active",
                "completed",
                "failed",
                "cancelled",
                name="taskstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("altitude_relative_m", sa.Float(), nullable=True),
        sa.Column("speed_mps", sa.Float(), nullable=True),
        sa.Column("start_delay_s", sa.Float(), nullable=True),
        sa.Column("created_at", fleet_service.db.types.UTCDateTime(length=27), nullable=False),
        sa.Column("updated_at", fleet_service.db.types.UTCDateTime(length=27), nullable=False),
        sa.ForeignKeyConstraint(
            ["aircraft_id"], ["aircraft.id"], name=op.f("fk_tasks_aircraft_id_aircraft")
        ),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
            name=op.f("fk_tasks_mission_id_missions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
        sa.UniqueConstraint(
            "mission_id", "aircraft_id", name=op.f("uq_tasks_mission_id_aircraft_id")
        ),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tasks_aircraft_id"), ["aircraft_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_mission_id"), ["mission_id"], unique=False)

    op.create_table(
        "waypoints",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("mission_id", sa.String(length=36), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("altitude_relative_m", sa.Float(), nullable=False),
        sa.Column("speed_mps", sa.Float(), nullable=True),
        sa.Column("loiter_s", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
            name=op.f("fk_waypoints_mission_id_missions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_waypoints")),
        sa.UniqueConstraint("mission_id", "seq", name=op.f("uq_waypoints_mission_id_seq")),
    )
    with op.batch_alter_table("waypoints", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_waypoints_mission_id"), ["mission_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Migrations are forward-only (ADR 0016); restore the pre-upgrade backup instead."""
    raise NotImplementedError("forward-only migrations: restore data/backups/ops-*.db")
