"""command confirmation and override

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-28 12:37:29.307938
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import fleet_service.db.types

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("command_targets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("reason_code", sa.String(length=32), nullable=True))

    with op.batch_alter_table("commands", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "confirmation_expires_at",
                fleet_service.db.types.UTCDateTime(length=27),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column("override", sa.Boolean(), server_default=sa.text("0"), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Migrations are forward-only (ADR 0016); restore the pre-upgrade backup instead."""
    raise NotImplementedError("forward-only migrations: restore data/backups/ops-*.db")
