"""mission plans and points of interest

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-30 12:13:33.787462
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import fleet_service.db.types

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pois",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("incident_id", sa.String(length=36), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "poi",
                "survivor_sighting",
                "clue",
                "hazard",
                name="poikind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "confirmed",
                "dismissed",
                "resolved",
                name="poistatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("uncertainty_m", sa.Float(), nullable=True),
        sa.Column("aircraft_id", sa.String(length=36), nullable=True),
        sa.Column("reported_at", fleet_service.db.types.UTCDateTime(length=27), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", fleet_service.db.types.UTCDateTime(length=27), nullable=False),
        sa.Column("updated_at", fleet_service.db.types.UTCDateTime(length=27), nullable=False),
        sa.ForeignKeyConstraint(
            ["aircraft_id"],
            ["aircraft.id"],
            name=op.f("fk_pois_aircraft_id_aircraft"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_pois_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"], ["incidents.id"], name=op.f("fk_pois_incident_id_incidents")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pois")),
    )
    with op.batch_alter_table("pois", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pois_aircraft_id"), ["aircraft_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_pois_incident_id"), ["incident_id"], unique=False)

    with op.batch_alter_table("aircraft", schema=None) as batch_op:
        batch_op.add_column(sa.Column("endurance_s", sa.Float(), nullable=True))

    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("escalated_at", fleet_service.db.types.UTCDateTime(length=27), nullable=True)
        )

    with op.batch_alter_table("missions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("plan", sa.JSON(), nullable=True))

    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("route", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("plan", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Migrations are forward-only (ADR 0016); restore the pre-upgrade backup instead."""
    raise NotImplementedError("forward-only migrations: restore data/backups/ops-*.db")
