"""
Entity identifiers: UUIDv7 (RFC 9562), so ids sort by creation time (ADR 0007).

``uuid.uuid7`` only exists from Python 3.14; the container runs 3.12. Within one
millisecond the random part is incremented instead of redrawn, so ids generated by
this process are strictly increasing, which keeps cursor pagination in creation order.
"""

import os
import threading
import time
import uuid

_RAND_BITS = 74  # 128 - 48 timestamp bits - 4 version bits - 2 variant bits
_lock = threading.Lock()
_last_ms = -1
_last_rand = 0


def uuid7(unix_ms: int | None = None) -> uuid.UUID:
    """Return a new, process-monotonic UUIDv7."""
    global _last_ms, _last_rand
    with _lock:
        ms = time.time_ns() // 1_000_000 if unix_ms is None else unix_ms
        if ms <= _last_ms:
            ms = _last_ms
            rand = _last_rand + 1
            if rand >= 1 << _RAND_BITS:  # 2^74 ids in one millisecond: borrow the next one
                ms, rand = ms + 1, int.from_bytes(os.urandom(10)) >> 6
        else:
            rand = int.from_bytes(os.urandom(10)) >> 6
        _last_ms, _last_rand = ms, rand
    rand_a, rand_b = rand >> 62, rand & ((1 << 62) - 1)
    value = (ms & ((1 << 48) - 1)) << 80 | 0x7 << 76 | rand_a << 64 | 0b10 << 62 | rand_b
    return uuid.UUID(int=value)


def new_id() -> str:
    """Return a new entity id as a canonical lower-case UUID string."""
    return str(uuid7())
