"""
Generate a PX4 SIH fleet of any size for scale runs (ADR 0026).

The image, the parameters and the airplane's takeoff settings are read from
``compose.yaml`` (the five-aircraft fleet), so both fleets fly the same PX4. Instance *i*
has MAVLink system id *i+1*; homes are on a grid, 25 m apart, 10 per row, starting at
the PX4 default home. Every fifth aircraft is an airplane.

    python sim/sitl/fleet.py --count 50 --out sim/sitl/generated
    docker compose -f sim/sitl/generated/compose.yaml up -d

Writes ``compose.yaml`` and ``fleet.json`` (system id, callsign, airframe per aircraft),
which the scale test reads.
"""

import argparse
import copy
import json
from pathlib import Path
from typing import Any

import yaml

HERE = Path(__file__).resolve().parent
BASE = HERE / "compose.yaml"
AIRPLANE_SERVICE = "px4-3"  # the airplane of the base fleet, whose settings are copied

HOME_LAT = 47.397742
HOME_LON = 8.545594
SPACING_M = 25.0
PER_ROW = 10
LAT_DEG_PER_M = 1.0 / 111_195.0
LON_DEG_PER_M = 0.000331 / 25.0  # at the home latitude, as compose.yaml spaces homes
AIRPLANE_EVERY = 5
MAX_COUNT = 100


def home(instance: int) -> tuple[float, float]:
    """Latitude and longitude of an instance's home."""
    row, column = divmod(instance, PER_ROW)
    return (
        round(HOME_LAT + row * SPACING_M * LAT_DEG_PER_M, 7),
        round(HOME_LON + column * SPACING_M * LON_DEG_PER_M, 7),
    )


def is_airplane(instance: int) -> bool:
    """Every fifth aircraft (instances 4, 9, 14, ...) is an airplane."""
    return instance % AIRPLANE_EVERY == AIRPLANE_EVERY - 1


def generate(count: int) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    """The compose document and the fleet list for ``count`` aircraft."""
    if not 1 <= count <= MAX_COUNT:
        raise ValueError(f"count must be in [1, {MAX_COUNT}], got {count}")
    base = yaml.safe_load(BASE.read_text(encoding="utf-8"))
    template = base["x-px4"]
    airplane = base["services"][AIRPLANE_SERVICE]["environment"]
    airplane_env = {k: v for k, v in airplane.items() if k != "PX4_HOME_LON"}
    services: dict[str, Any] = {}
    fleet: list[dict[str, Any]] = []
    for instance in range(count):
        service = copy.deepcopy(template)
        env = service["environment"]
        if is_airplane(instance):
            env.update(airplane_env)
        latitude, longitude = home(instance)
        env["PX4_HOME_LAT"] = f"{latitude:.7f}"
        env["PX4_HOME_LON"] = f"{longitude:.7f}"
        service["command"] = ["-d", "-i", str(instance)]
        services[f"px4-{instance}"] = service
        system_id = instance + 1
        fleet.append(
            {
                "system_id": system_id,
                "callsign": f"{'FW' if is_airplane(instance) else 'HX'}-{system_id:02d}",
                "airframe": "fixed_wing" if is_airplane(instance) else "multirotor_hexa",
                "home_latitude": latitude,
                "home_longitude": longitude,
            }
        )
    return {"name": "px4-scale", "services": services}, fleet


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--count", type=int, required=True, help=f"aircraft, 1 to {MAX_COUNT}")
    parser.add_argument("--out", type=Path, default=HERE / "generated")
    args = parser.parse_args()
    compose, fleet = generate(args.count)
    args.out.mkdir(parents=True, exist_ok=True)
    header = f"# Generated by sim/sitl/fleet.py --count {args.count}; do not edit.\n"
    (args.out / "compose.yaml").write_text(
        header + yaml.safe_dump(compose, sort_keys=False), encoding="utf-8"
    )
    (args.out / "fleet.json").write_text(json.dumps(fleet, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
