"""
Strict stand-ins for rosidl-generated Python message classes.

Classes are generated by parsing ``.msg`` definitions and enforce the same
assignment rules as rosidl_generator_py:

* only declared fields exist (``__slots__``);
* ``float32/64`` fields require ``float`` (``int`` and ``np.float32`` are rejected);
* integer fields require ``int`` within range (``bool`` and ``np.int64`` are rejected);
* ``bool`` fields require ``bool``; ``string`` fields require ``str``;
* fixed-size numeric arrays accept a numpy array of the exact dtype and size,
  or a sequence of the exact length, and are stored as numpy arrays;
* unbounded numeric sequences accept ``array.array`` with the right type code
  or a real sequence of the right element type (a numpy array is rejected);
* nested message fields require an instance of the nested class.

Definitions come from three places: this repository's
``swarm_sar_interfaces/msg``; verbatim copies of the official ROS 2 Jazzy
definitions (ros2/common_interfaces and ros2/rcl_interfaces, Apache-2.0);
and verbatim copies of PX4's definitions from ``PX4/px4_msgs`` branch
``release/1.15`` (BSD-3-Clause), all under ``msg_fixtures/<package>/``. So the
codec and adapters are tested against the real field names, types and
constants without a ROS 2 installation.
"""

import array
from collections.abc import Sequence, Set
import pathlib
import re

import numpy as np

_FIELD_NAME = re.compile(r'^[a-z][a-z0-9]*(_[a-z0-9]+)*$')
_CONSTANT_NAME = re.compile(r'^[A-Z][A-Z0-9_]*$')

_INT_RANGES = {
    'int8': (-2 ** 7, 2 ** 7 - 1), 'uint8': (0, 2 ** 8 - 1),
    'int16': (-2 ** 15, 2 ** 15 - 1), 'uint16': (0, 2 ** 16 - 1),
    'int32': (-2 ** 31, 2 ** 31 - 1), 'uint32': (0, 2 ** 32 - 1),
    'int64': (-2 ** 63, 2 ** 63 - 1), 'uint64': (0, 2 ** 64 - 1),
    'byte': (0, 255), 'char': (0, 255),
}
_FLOATS = {'float32': 3.402823466e+38, 'float64': 1.7976931348623157e+308}
_TYPECODES = {'float32': 'f', 'float64': 'd', 'int8': 'b', 'uint8': 'B', 'int16': 'h',
              'uint16': 'H', 'int32': 'i', 'uint32': 'I', 'int64': 'q', 'uint64': 'Q'}
_DTYPES = {'float32': np.float32, 'float64': np.float64, 'int8': np.int8, 'uint8': np.uint8,
           'int16': np.int16, 'uint16': np.uint16, 'int32': np.int32, 'uint32': np.uint32,
           'int64': np.int64, 'uint64': np.uint64}

TEST_DIR = pathlib.Path(__file__).resolve().parent
FIXTURES_DIR = TEST_DIR / 'msg_fixtures'
INTERFACES_DIR = TEST_DIR.parents[1] / 'swarm_sar_interfaces' / 'msg'


class _Field:
    """One parsed field of a message definition."""

    def __init__(self, name, base, array_size, default):
        self.name = name
        self.base = base            # 'float64' or 'pkg/Type'
        self.array_size = array_size  # None = scalar, -1 = unbounded, n = fixed
        self.default = default


class FakeMessages:
    """Registry that lazily builds fake message classes from definitions."""

    def __init__(self):
        self._definitions = {}
        for package_dir in sorted(p for p in FIXTURES_DIR.iterdir() if p.is_dir()):
            for path in sorted(package_dir.glob('*.msg')):
                self._definitions[f'{package_dir.name}/{path.stem}'] = path.read_text()
        for path in sorted(INTERFACES_DIR.glob('*.msg')):
            self._definitions[f'swarm_sar_interfaces/{path.stem}'] = path.read_text()
        self._classes = {}

    def get(self, full_name):
        """Return the fake class for ``pkg/Type``."""
        if full_name not in self._classes:
            if full_name not in self._definitions:
                raise KeyError(f'no definition for {full_name}')
            self._classes[full_name] = self._build(full_name)
        return self._classes[full_name]

    def _build(self, full_name):
        package = full_name.split('/')[0]
        fields, constants = parse_definition(self._definitions[full_name], package)
        for field in fields:
            if '/' in field.base:
                self.get(field.base)  # resolve eagerly so bad references fail at build time
        registry = self

        def __init__(self, **kwargs):  # noqa: N807
            for field in fields:
                setattr(self, field.name, _default(field, registry))
            for key, value in kwargs.items():
                if key not in {f.name for f in fields}:
                    raise TypeError(f'{full_name} has no field {key!r}')
                setattr(self, key, value)

        namespace = {'__slots__': tuple('_' + f.name for f in fields), '__init__': __init__,
                     '__repr__': lambda self: f'{full_name}(...)'}
        for field in fields:
            namespace[field.name] = _property(field, registry, full_name)
        namespace.update(constants)
        return type(full_name.replace('/', '_'), (object,), namespace)


def parse_definition(text, package):
    """Parse a .msg definition into fields and constants, enforcing rosidl naming rules."""
    fields, constants = [], {}
    for raw in text.splitlines():
        line = raw.split('#', 1)[0].strip()
        if not line:
            continue
        type_token, rest = line.split(None, 1)
        if '=' in rest:
            name, value = (part.strip() for part in rest.split('=', 1))
            if not _CONSTANT_NAME.match(name):
                raise ValueError(f'invalid constant name {name!r}')
            constants[name] = float(value) if type_token.startswith('float') else int(value)
            continue
        parts = rest.split()
        name = parts[0]
        if not _FIELD_NAME.match(name):
            raise ValueError(f'invalid field name {name!r} in {package}')
        default = parts[1] if len(parts) > 1 else None
        match = re.match(r'^([\w/]+)(\[(\d*)\])?$', type_token)
        if not match:
            raise ValueError(f'cannot parse type {type_token!r}')
        base = match.group(1)
        array_size = None
        if match.group(2):
            array_size = int(match.group(3)) if match.group(3) else -1
        if base not in _INT_RANGES and base not in _FLOATS and base not in ('bool', 'string'):
            if '/' not in base:
                base = f'{package}/{base}'
        fields.append(_Field(name, base, array_size, default))
    return fields, constants


def _is_nested(field):
    return '/' in field.base


def _default(field, registry):
    if field.array_size == -1:
        if _is_nested(field) or field.base in ('bool', 'string'):
            return []
        return array.array(_TYPECODES[field.base])
    if field.array_size is not None:
        if _is_nested(field):
            return [registry.get(field.base)() for _ in range(field.array_size)]
        return np.zeros(field.array_size, dtype=_DTYPES[field.base])
    if _is_nested(field):
        return registry.get(field.base)()
    if field.base == 'bool':
        return False
    if field.base == 'string':
        return ''
    if field.base in _FLOATS:
        return float(field.default) if field.default is not None else 0.0
    return int(field.default) if field.default is not None else 0


def _check_scalar(field, value, registry, owner):
    base = field.base
    where = f'{owner}.{field.name}'
    if _is_nested(field):
        assert isinstance(value, registry.get(base)), f'{where} must be a {base}'
    elif base == 'bool':
        assert isinstance(value, bool), f'{where} must be bool, got {type(value).__name__}'
    elif base == 'string':
        assert isinstance(value, str), f'{where} must be str, got {type(value).__name__}'
    elif base in _FLOATS:
        assert isinstance(value, float), f'{where} must be float, got {type(value).__name__}'
        limit = _FLOATS[base]
        assert value != value or abs(value) <= limit or abs(value) == float('inf'), \
            f'{where} out of range'
    else:
        low, high = _INT_RANGES[base]
        assert isinstance(value, int) and not isinstance(value, bool), \
            f'{where} must be int, got {type(value).__name__}'
        assert low <= value <= high, f'{where}={value} out of [{low}, {high}]'


def _property(field, registry, owner):
    slot = '_' + field.name

    def getter(self):
        return getattr(self, slot)

    def setter(self, value):
        where = f'{owner}.{field.name}'
        if field.array_size is None:
            _check_scalar(field, value, registry, owner)
        elif field.array_size >= 0 and not _is_nested(field) and field.base in _DTYPES:
            if isinstance(value, np.ndarray):
                assert value.dtype == _DTYPES[field.base], f'{where} dtype must be {field.base}'
                assert value.size == field.array_size, f'{where} needs {field.array_size} items'
            else:
                assert isinstance(value, Sequence) and not isinstance(value, str), \
                    f'{where} must be a sequence'
                assert len(value) == field.array_size, f'{where} needs {field.array_size} items'
                for item in value:
                    _check_scalar(field, item, registry, owner)
                value = np.array(value, dtype=_DTYPES[field.base])
        elif field.array_size == -1 and not _is_nested(field) and field.base in _TYPECODES:
            if isinstance(value, array.array):
                assert value.typecode == _TYPECODES[field.base], f'{where} typecode mismatch'
            else:
                assert isinstance(value, (Sequence, Set)) and not isinstance(value, str), \
                    f'{where} must be array.array or a sequence (not {type(value).__name__})'
                for item in value:
                    _check_scalar(field, item, registry, owner)
                value = array.array(_TYPECODES[field.base], value)
        else:
            assert isinstance(value, (Sequence, Set)) and not isinstance(value, str), \
                f'{where} must be a sequence'
            for item in value:
                _check_scalar(field, item, registry, owner)
            value = list(value)
        setattr(self, slot, value)

    return property(getter, setter)
