"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-28 11:25:47.558282
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telemetry_samples",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("aircraft_id", sa.String(length=36), nullable=False),
        sa.Column("ts_us", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("altitude_amsl_m", sa.Float(), nullable=True),
        sa.Column("altitude_relative_m", sa.Float(), nullable=True),
        sa.Column("heading_deg", sa.Float(), nullable=True),
        sa.Column("groundspeed_mps", sa.Float(), nullable=True),
        sa.Column("climb_rate_mps", sa.Float(), nullable=True),
        sa.Column("battery_pct", sa.Float(), nullable=True),
        sa.Column("battery_v", sa.Float(), nullable=True),
        sa.Column("gps_fix", sa.Integer(), nullable=True),
        sa.Column("satellites", sa.Integer(), nullable=True),
        sa.Column("flight_mode", sa.String(length=32), nullable=True),
        sa.Column("armed", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telemetry_samples")),
    )
    with op.batch_alter_table("telemetry_samples", schema=None) as batch_op:
        batch_op.create_index(
            "ix_telemetry_samples_aircraft_ts", ["aircraft_id", "ts_us"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Migrations are forward-only (ADR 0016); restore the pre-upgrade backup instead."""
    raise NotImplementedError("forward-only migrations")
