"""sample in_air

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-28 12:37:32.888697
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("telemetry_samples", schema=None) as batch_op:
        batch_op.add_column(sa.Column("in_air", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Migrations are forward-only (ADR 0016); restore the pre-upgrade backup instead."""
    raise NotImplementedError("forward-only migrations")
